server:
  port: 8085   # QA environment port

spring:
  datasource:
    url: jdbc:mysql://qa-db-server:3306/orderdb_qa
    username: order_qa
    password: qa123

# Optional: logging for QA
logging:
  level:
    root: INFO
    com.yourcompany.orderservice: DEBUG

# Optional: any QA-specific feature flags
feature:
  enable-new-checkout: true
